### ISSUE TITLE
Add a file

### ISSUE THREAD

**Issue by vtthdf** [mastervanleeuwen/J-TrackGallery#13] opened 2021-12-27 12:41 UTC
Bonjour Marco, 
Je termine le transfert pour la nouvelle version de joomla 4
J’ai installé J-TrackGallery. je rencontre un problème avec l’enregistrement des nouvelles traces. Quand je crée un lien « menu » pour enregistrer une nouvelle trace, cela fonctionne. Le lien du composant « Ajouter un fichier » ne fonctionne pas très bien. Il n’y a pas la possibilité d’importer un fichier. 
Cordialement. Pascal.
  
Hello Marco,
I finish the transfer for the new version of joomla 4
I installed J-TrackGallery. I'm having a problem with saving new tracks. When I create a "menu" link to record a new track, it works. The link of the "Add File" component does not work very well. There is no possibility to import a file.
Cordially. Pascal.
![ScreenShot_20211227132611](https://user-images.githubusercontent.com/50077802/147472667-5b6a3f29-c18f-4164-8598-7446d3b441a3.jpeg)

**Comment by mastervanleeuwen** [comment] 2021-12-27 22:05
Hello Pascal,

Thanks for the report. I have tested this on my Joomla 4 test site and it works on my server, so wonder whether this could be a problem with the file size limit for uploading files, or another permission setting or configuration in Joomla.  Could you check whether the directory that is shown in the error message (/home/vtthautsdefrance/steoc.vtt-hautsdefrance.fr/images/jtrackgallry/uploaded_track/)  exists?

The other problem that you reported, with adding/editing categories in the admin view has been fixed in this version:
https://github.com/mastervanleeuwen/J-TrackGallery/archive/refs/tags/0.9.33c.zip

Please let me know if this version works for you.

Best regards, Marco.

-------------------------------------------------------------

Bonjour Pascale,

Merci pour le rapport. J'ai testé cela sur mon site de test Joomla 4 et cela fonctionne sur mon serveur; peut-être il y a un problème avec la limite de taille de fichier pour le téléchargement de fichiers, ou un autre paramètre d'autorisation ou configuration dans Joomla? Pourriez-vous vérifier si le répertoire qui est affiché dans le message d'erreur (/home/vtthautsdefrance/steoc.vtt-hautsdefrance.fr/images/jtrackgallry/uploaded_track/) existe ?

L'autre problème que vous avez signalé, avec l'ajout/la modification de catégories dans la vue administrateur a été corrigé dans cette version :
https://github.com/mastervanleeuwen/J-TrackGallery/archive/refs/tags/0.9.33c.zip

S'il vous plaît laissez-moi savoir si cette version fonctionne pour vous.

Cordialement, Marco.

**Comment by vtthdf** [comment] 2021-12-28 08:13
Bonjour Marco, 
le fichier existe mais avec un S à la fin.
pour info j'ai importé la base de donnée des traces de jtrackgallry dans la nouvelle base en la renommant. j'ai aussi importé les fichiers image/jtrackgallry.
Cordialement pascal

Hello Marco,
the file exists but with an S at the end.
for info I imported the jtrackgallry traces database into the new database by renaming it. I also imported the image / jtrackgallry files.
Sincerely pascal

![ScreenShot_20211228091143](https://user-images.githubusercontent.com/50077802/147544290-cc52de4f-b2d9-4227-bb6c-18072236bbc8.jpeg)

**Comment by mastervanleeuwen** [comment] 2021-12-28 10:07
Dear Pascal,

I see; I am not sure what the problem is, so let's try to find out. Could you look inside the 'uploaded_tracks' directory to see whether the file that you were trying to upload is present? If you try to upload a file with a name that already exists, there should be an error message.

Are you comfortable with editing the php code? The code that uploads the file and stores everything in the database is in components/com_jtg/models/track.php, the saveFile() function. You could add a line:
`error_log('Uploading file '.$filename);`
after  line 214:
https://github.com/mastervanleeuwen/J-TrackGallery/blob/master/components/com_jtg/models/track.php#L214
This will add al line in the log file (error_log on your webserver), showing the file name of the file that you were uploading. The next step would be to check that adding the file to the database works (line 300) and then that it gets the correct track ID (line 305). If you don't know how to do this, I can also help with it, just let me know.

Best regards, Marco.

**Comment by vtthdf** [comment] 2021-12-28 10:19
malheureusement je ne suis pas trop à l'aise avec l'édition pour les codes PHP.
voulez-vous que je vous envoie un compte admin du site par mail ? 

unfortunately I'm not too comfortable with editing for PHP codes.
do you want me to send you an admin account of the site by email?

**Comment by mastervanleeuwen** [comment] 2021-12-28 12:33
Dear Pascal,
Yes, if you could send me an admin account via e-mail, I will have a look to try and understand the problem.
Best regards, Marco.

**Comment by vtthdf** [comment] 2021-12-28 12:55
Mail envoyé.
Merci pascal.

E-mail sent.
Thanks pascal.

**Comment by mastervanleeuwen** [comment] 2021-12-28 14:23
Hi Pascal,

Thanks for providing access to your site. The problem is fixed on your site now and I will also include the fix in the next update. 

In case you are interested in the details: for some reason, the 'id' variable was set, while it should be empty when adding a new track. I am not quite sure why this happened, it could be some interference from/by another component, but I did find a way to unset it. I am thinking of implementing a better solution in the future, but the current solution already works.

Best regards, Marco.

**Comment by vtthdf** [comment] 2021-12-28 14:32
merci pour la correction. je viens de faire un test quand je reçois l'email d'une nouvelle trace sur le lien il a une erreur et la trace est déjà publié.
https://siteoc.vtt-hautsdefrance.fr/index.php?option=com_jtg&view=files&layout=file&id=166
Cordialement pascal

thank you for the correction. I just did a test when I receive the email of a new trace on the link it has an error and the trace is already published.
https://siteoc.vtt-hautsdefrance.fr/index.php?option=com_jtg&view=files&layout=file&id=166
Sincerely pascal

**Comment by mastervanleeuwen** [comment] 2021-12-28 15:00
I see, this is a leftover of some older code. It should be fixed now as well.
The format of the links has changed, it should be: https://siteoc.vtt-hautsdefrance.fr/index.php?option=com_jtg&view=track&layout=default&id=166
It will be fixed in future e-mails

**Comment by vtthdf** [comment] 2021-12-30 09:52
Bonjour Marco, sur le site je me retrouve avec un espace vide entre la carte et le tableau en dessous. 
![ScreenShot_20211230104838](https://user-images.githubusercontent.com/50077802/147740758-59fe3a86-5357-4792-9c84-3f6e960c18fb.jpeg)
Cordialement. Pascal. 

Hello Marco, on the site I find myself with an empty space between the card and the table below.
![ScreenShot_20211230104838](https://user-images.githubusercontent.com/50077802/147740758-59fe3a86-5357-4792-9c84-3f6e960c18fb.jpeg)
Cordially. Pascal.

**Comment by mastervanleeuwen** [comment] 2021-12-30 12:33
Hi Pascal,

This is now fixed as well. It turns out that you had added some html code to the introduction text (in the global configuration) which contained a 'div' with the name 'olMap', which confused the layout. This was probably a leftover from a previous test or debugging session. I removed this code and now it looks better.

Best  regards, Marco.

**Comment by vtthdf** [comment] 2022-03-08 17:54
Bonjour Marco,
Pour mon deuxième site je termine le transfert pour la nouvelle version de joomla 4
J’ai installé J-TrackGallery et importé la base de donnée de mon ancien site. Je rencontre le même problème que tu as corrigé avec mon autre site.
L’enregistrement des nouvelles traces et l’affichage de la carte. 
Voici le lien : https://www.copievopourvtthdf.vtt-hautsdefrance.fr/index.php/parcours-carte-gps-vtt-cyclo-hdf/jtg

Cordialement. Pascal

Hello Marco,
For my second site I finish the transfer for the new version of joomla 4
I installed J-TrackGallery and imported the database from my old site. I'm having the same problem you fixed with my other site.
Recording new tracks and displaying the map
Here is the link : https://www.copievopourvtthdf.vtt-hautsdefrance.fr/index.php/parcours-carte-gps-vtt-cyclo-hdf/jtg

Cordially. Pascal

**Comment by mastervanleeuwen** [comment] 2022-03-08 21:36
Dear Pascal,

Thanks for your message.

To fix the problem with the overview map, you have to update the map configurations, please update to the latest version:

https://github.com/mastervanleeuwen/J-TrackGallery/releases/tag/0.9.34-rc4

and check the settings for the Mapnik map: 

<img width="1244" alt="image" src="https://user-images.githubusercontent.com/14343699/157327888-71e140b0-e5ee-43eb-b620-512df94b7136.png">

make sure that most of the fields are empty like in the example above. This is a one-time change.

The problem with adding tracks should have been fixed in the recent versions. Could you try again and let me know if it is still there?

Best regards, Marco.

**Comment by vtthdf** [comment] 2022-03-09 12:01
Hello Marco, nothing changes :(

Sincerely Easter

**Comment by mastervanleeuwen** [comment] 2022-03-09 15:13
Dear Pascal,

It looks like the map configuration is not changed yet. Could you check in the administrator view, as shown above (under J!Trackgallery -> maps, choose the first map in the list to edit).

If you would like, I can also try to help with the configuration directly, if you set up an account for me (the account for the other site does not work here).

Best regards, Marco.

**Comment by vtthdf** [comment] 2022-03-09 17:31
Hello Marco,
unable to delete line.
I just created an admin access these are the same as the other site.
Thanks Pascal.

**Comment by mastervanleeuwen** [comment] 2022-03-09 20:13
Hi Pascal,

The account works, but I do not have administrator acces, which is needed to change the map settings.

What is the error message that you get when deleting the line?

Best regards, Marco.

**Comment by vtthdf** [comment] 2022-03-09 20:58
here it is changed
Pascal

**Comment by mastervanleeuwen** [comment] 2022-03-09 21:53
Thanks Pascal,

There was a database error due to a bug that I had introduced in an older version. This is fixed now, and I think everything works. Let me know if you encounter any other problems.

Best regards, Marco.

**Comment by vtthdf** [comment] 2022-03-10 06:57
hello marco, problem with the phone. thank you pascal
![Screenshot_20220310-074733_Messenger](https://user-images.githubusercontent.com/50077802/157606338-762c5f54-fa22-4be5-886c-09834af0ee97.jpg)

**Comment by vtthdf** [comment] 2022-03-11 06:54
hello marco, looking with the phone the nails to download a trace appears and disappears thank you pascal

**Comment by mastervanleeuwen** [comment] 2022-03-12 13:41
Dear Pascal,

Thanks you for the reports.

The problem with the page for uploading new files is now fixed on your second site: https://www.copievopourvtthdf.vtt-hautsdefrance.fr/
I plan to release a new version with this fix soon.

I tried to reproduce the problem with the download buttons on my phone, but there it works fine. I tried both with the Safari and Chrome browsers. Which phone/system and browser are you using? Could you send me a screen shot with the problem?

Note that the download buttons only appear when you are logged in as a user. If you prefer to allow everybody to download files (also without logging in), you can change this in the settings, by giving 'Public' permission to download.

Best regards, Marco.

**Comment by mastervanleeuwen** [comment] 2024-11-02 19:50
This has been resolved. If anything else comes up, do not hesitate to open a new issue.

**Closed by mastervanleeuwen** 2024-11-02 19:50 UTC
