### ISSUE TITLE
The map does not appear if there are many tracks.

### ISSUE THREAD

**Issue by camminateinfriuli** [mastervanleeuwen/J-TrackGallery#57] opened 2023-05-22 19:52 UTC
In the overview map, if there are many tracks, the map does not appear, perhaps it is possible to carry out more groupings and view the map. it's bad that the map doesn't appear at all without any message.

**Comment by mastervanleeuwen** [comment] 2023-05-23 19:56
Hmm, that is strange. How many tracks do you have approximately? Is it around 50, or more than 100?

Do you have a web site that I can access to see the effect? If not, could you check the 'error_log' file to see whether there are any errors or warnings? In addition, can you use the 'View source' option in the browser to see the html page and check whether you see this section:
```
<div id="jtg_map" class="olMap"></div>
```
and later on:

```
<script type="text/javascript">
  jtgBaseUrl = "https://testing.gta-trek.eu/";
  jtgTemplateUrl = "https://testing.gta-trek.eu/components/com_jtg/assets/template/default";
  jtgMapInit('Kaartlagen','jtg_map');
  jtgMap.addControl(new ol.control.ScaleLine({units: 'metric'}));
  jtgMap.addControl(new ol.control.MousePosition( {coordinateFormat: ol.coordinate.createStringXY(4), projection: 'EPSG:4326' } ));
  jtgMap.addControl(new ol.control.ZoomSlider());
  jtgAddMapLayer(0,'','','OSM Mapnik', true);
  tracks = [{		"lon" : -1.8294689814,
  "lat" : 53.4947858175,
 
```
The last bit should be an array with tracks, the longitude and latitude will be different in your case.

If this test appears, can you open the developer view in the browser to look for JavaScript errors?

**Comment by camminateinfriuli** [comment] 2023-05-24 00:08
I have a few hundred tracks, up to a little more than a hundred tracks, the map can be seen and then it doesn't appear at all, perhaps it would be enough to make more groupings. I can give you access to the staging site if you want to try

**Comment by mastervanleeuwen** [comment] 2023-05-26 20:05
I see.  I checked in the code, but did not find any explicit limitation on the number of tracks. 

Could you have a look at your page with 'view source' to look for the sections of code that I highlighted above? It would also be useful to use the 'developer tools' from your web browser (Google Chrome has it, I think Firefox as well, not sure about other browsers) to see whether there is a JavaScript error in the 'console' window of the developer tools.

If you could post a link to the frontend of your staging site, I can also have a look myself with the tools I mention above; this will help narrow down the possible causes.

Best regards, Marco.

**Comment by camminateinfriuli** [comment] 2023-05-30 14:10
> Hmm, that is strange. How many tracks do you have approximately? Is it around 50, or more than 100?
> 
> Do you have a web site that I can access to see the effect? If not, could you check the 'error_log' file to see whether there are any errors or warnings? In addition, can you use the 'View source' option in the browser to see the html page and check whether you see this section:
> 
> ```
> <div id="jtg_map" class="olMap"></div>
> ```
> 
> and later on:
> 
> ```
> <script type="text/javascript">
>   jtgBaseUrl = "https://testing.gta-trek.eu/";
>   jtgTemplateUrl = "https://testing.gta-trek.eu/components/com_jtg/assets/template/default";
>   jtgMapInit('Kaartlagen','jtg_map');
>   jtgMap.addControl(new ol.control.ScaleLine({units: 'metric'}));
>   jtgMap.addControl(new ol.control.MousePosition( {coordinateFormat: ol.coordinate.createStringXY(4), projection: 'EPSG:4326' } ));
>   jtgMap.addControl(new ol.control.ZoomSlider());
>   jtgAddMapLayer(0,'','','OSM Mapnik', true);
>   tracks = [{		"lon" : -1.8294689814,
>   "lat" : 53.4947858175,
>  
> ```
> 
> The last bit should be an array with tracks, the longitude and latitude will be different in your case.
> 
> If this test appears, can you open the developer view in the browser to look for JavaScript errors?

I have already tried to make a diagnostic, with the 'developer tools', when you told me to check everything is there including the array with traces but the map is not displayed.

[https://camminateinfriuli.it/index.php/articoli/info-tracce/jtg?introtext=1](url)

and 
[view-source:https://camminateinfriuli.it/index.php/articoli/info-tracce/jtg?introtext=1](url)

**Comment by mastervanleeuwen** [comment] 2023-06-02 21:46
Thanks for the link to the page, this really helps to narrow down the problem. Something seems to have gone wrong with parsing this track:
https://camminateinfriuli.it/index.php/articoli/info-tracce/track/132
It is not yet clear to me what really went wrong here. Could you maybe send me the gpx file, so that I can use it to debug the code?

In case you are interested in a bit more detail: I used the console in the 'developer view', which shows this error:
<img width="348" alt="image" src="https://github.com/mastervanleeuwen/J-TrackGallery/assets/23643853/0512273c-cb57-4f3f-94fb-39ce6e8e0af6">
Then, when looking at the view-source, line 1533, it reads:
```
,{ "lon" : 46.2729, 13.01120,
   "lat" : 46.2729, 13.01120,
   "catIdx" : '0',

```
which is strange; the latitude and longitude should be a single number, not two numbers. I am not sure how this can happen, but it clearly shows that there is a bug in the code somehow.

**Comment by camminateinfriuli** [comment] 2023-06-08 16:48
sorry for the delay, I didn't see your message, how do I attach the track? I try to delete it to see if the map appears.

**Comment by camminateinfriuli** [comment] 2023-06-08 16:57
in effect by eliminating that track the map appears again it is too crowded because it does not create groupings, but it does appear. then there are also bugs in the display of geolocated photos in the track, some photos are moved to a different place

**Comment by camminateinfriuli** [comment] 2023-06-11 11:30
Thank you for your tireless availability.

I'm attaching the track in question so you can analyze it, in fact it's the one causing problems.

The download doesn't work for me but it's probably my fault, and it's not important to me.

More effective grouping would make the map more readable.

Here are some links with photos not geolocated correctly, maybe because I added more than 10? however some photos are in a position that seems fixed and that does not depend on the coordinates of the photo, just reduce the zoom and you see their incorrect position, I put the link of three tracks that have this problem.

https://camminateinfriuli.it/index.php/articoli/info-tracce/panoramica-tracce/track/119
https://camminateinfriuli.it/index.php/articoli/info-tracce/panoramica-tracce/track/278
https://camminateinfriuli.it/index.php/articoli/info-tracce/panoramica-tracce/track/301

I thank you infinitely
[cuareflajel.zip](https://github.com/mastervanleeuwen/J-TrackGallery/files/11714470/cuareflajel.zip)

**Comment by mastervanleeuwen** [comment] 2023-06-18 10:39
Hi,

I tested the cuareflajel track and when I upload it, it is parse correctly: https://testing.gta-trek.eu/index.php/nl/j-trackgallery/track/18. I think that the problem with this track may have been caused by an old version of the code. Could you try reuploading it to see whether it works now on your site as well?

The clustering of icons in the overview map is done by the code from the openlayers toolkit. I agree that is seems to behave strangely, leaving some tracks out of the clusters. I have updated the openlayers toolkit to v6.15.1. Could you try the new version here:
https://github.com/mastervanleeuwen/J-TrackGallery/releases/tag/0.9.34-rc33
to see whether that helps? I have also made some improvements to the code that handles the popups in the overview map.

Concerning the photos that appear in the wrong location, I would need some more information to understand what is happening. The position of the photos on the map is determined by the geolocation information that is stored in the photo. Most image/photo browsers can show this information. Could you check for example for this photo:
<img width="666" alt="image" src="https://github.com/mastervanleeuwen/J-TrackGallery/assets/23643853/cbaba01d-68c3-4233-8936-816ead191f2e">
by looking at the 'file/photo information'. There is a section called 'EXIF data' which shows the geolocation. If you cannot find it, could you attach the original photo on the forum, so that I can have a look?

Best regards, Marco.

**Comment by camminateinfriuli** [comment] 2023-06-21 16:44
I hadn't eliminated the offending track, I had only changed from published to unpublished track with ID303, unfortunately if I publish it the panoramic map disappears again.

I updated to RC 0.33 but didn't notice any changes the grouping of tracks on the overview map is still confusing.

As for the positioning in geolocation of the photos, it is not a problem of the photo(s), perhaps it is a problem of the quantity of the photos, however I am attaching the photo, but the problem is on all tracks when I add more geolocated photos.

to get you access to my Stagging site where you can try whatever you want if it helps I created an account

Link to access the Stagging site: http://camminateinfriuli.it/livestaging/ERG1ab6a519dad728939b428bfef6de1009e9d7178342d3be8bce6bc30258296c03T
User: mastervanleeuwen
Password: jtrack1234

![IMG_20230521_115254](https://github.com/mastervanleeuwen/J-TrackGallery/assets/68971180/eeb77329-ccac-4df8-97c9-7c7d98d9ad9d)

**Comment by mastervanleeuwen** [comment] 2023-06-25 14:46
Thanks for uploading the picture. I checked the latitude and longitude data in the picture, and get the following:
<img width="185" alt="image" src="https://github.com/mastervanleeuwen/J-TrackGallery/assets/23643853/14e1722b-4943-4a72-8df3-41663d218a66">
this matches with where the picture is shown on the map, for example the longitude: 13 degrees 7 minutes 10.895 seconds is 13 degrees + 7/60 + 10.895/3600 = 13.1198 decimal degrees. At the moment, there is no easy way to change this; I am considering to implement the possibility to change the coordinates by hand after uploading the picture.

**Comment by mastervanleeuwen** [comment] 2023-07-15 19:51
I found a solution for the problem with the overlapping icons in the overview map, by setting a larger minimum distance between the icons. This is implemented in the new pre-release:

https://github.com/mastervanleeuwen/J-TrackGallery/releases/tag/0.9.34-rc34

**Comment by mastervanleeuwen** [comment] 2023-07-23 19:38
Hi again,

I also implemented a solution for the pictures that appear in the wrong location: you can now edit the geolocation of the photos that are added to a track in the front-end track edit view. In this view, the coordinates appear below each photo; you can edit them manually, or click the button 'Select on map', which allows you to pick the coordinates by clicking on the map. Note that the coordinates are only updated when you save the changes, so the photo icon does not move immediately.

This is available in the latest version: https://github.com/mastervanleeuwen/J-TrackGallery/releases/tag/0.9.34-rc36

**Comment by camminateinfriuli** [comment] 2023-07-30 20:08
Thanke you very much.

Il dom 23 lug 2023, 21:39 Marco van Leeuwen ***@***.***> ha
scritto:

**Comment by camminateinfriuli** [comment] 2023-07-31 17:01
During install RC36 return error

[image: RC36-install.png]

Il giorno dom 30 lug 2023 alle ore 22:08 Camminate in Friuli <
***@***.***> ha scritto:

**Comment by camminateinfriuli** [comment] 2023-07-31 17:05
Il giorno lun 31 lug 2023 alle ore 19:01 Camminate in Friuli <
***@***.***> ha scritto:

**Comment by mastervanleeuwen** [comment] 2023-07-31 19:46
Unfortunately I do not see the picture of the error message; it was remove by github when posting the comment.

Are you getting a database error? If so, could you try this version:

https://github.com/mastervanleeuwen/J-TrackGallery/releases/tag/0.9.34-rc38

instead? I changed something in the SQL syntax to try and make it more robust. Unfortunately I could not easily test the change; please let me know whether it works.

Best regards, Marco.

**Comment by mastervanleeuwen** [comment] 2023-08-07 18:12
Hi,

The problem with displaying tracks in the overview map seems to be due to a
problem with extracting the start coordinates from the GPS file. In the
case that I looked at before, the latitude and longitude were shown twice,
which causes trouble with the mapping code.

Could you look up the problematic track in the administrator view and use
the button ‘recalculate calculated values’ to see whether this fixes the
issue?

Best regards,

Marco.


Op di 1 aug. 2023 om 19:00 schreef Camminate in Friuli <
***@***.***>

**Comment by camminateinfriuli** [comment] 2023-08-07 19:35
![image](https://github.com/mastervanleeuwen/J-TrackGallery/assets/68971180/d46fafb8-ad74-4651-9910-2e16f495da95)

**Comment by mastervanleeuwen** [comment] 2023-08-17 20:26
OK, great that the recalculation seems to work. I think that the problem with installing rc38 is a side-effect a previous failed update. I have made another change that I expect will solve this. Could you try the new version (it has the same version number, but contains an update):
https://github.com/mastervanleeuwen/J-TrackGallery/releases/tag/0.9.34-rc38

**Comment by camminateinfriuli** [comment] 2023-08-22 19:22
> OK, great that the recalculation seems to work. I think that the problem with installing rc38 is a side-effect a previous failed update. I have made another change that I expect will solve this. Could you try the new version (it has the same version number, but contains an update): https://github.com/mastervanleeuwen/J-TrackGallery/releases/tag/0.9.34-rc38

New version not is ready for me.


![Screenshot 2023-08-22 211744](https://github.com/mastervanleeuwen/J-TrackGallery/assets/68971180/c78f53f8-1698-496d-834b-0ed8693a9625)

**Comment by mastervanleeuwen** [comment] 2023-08-27 16:58
Sorry, I made a mistake with the previous update. Could you try this new version:

https://github.com/mastervanleeuwen/J-TrackGallery/releases/tag/0.9.34-rc39

Best regards, Marco.

**Comment by camminateinfriuli** [comment] 2023-08-28 18:52
i have the same error

**Comment by mastervanleeuwen** [comment] 2023-09-03 10:42
Glad to hear that it worked! RC39 contains a bug that breaks uploading tracks on the frontend (I was lazy and did not test this part). 
This should be fixed in RC40:
https://github.com/mastervanleeuwen/J-TrackGallery/releases/tag/0.9.34-rc40

**Comment by camminateinfriuli** [comment] 2023-09-05 20:53
I installed the RC40 version but it doesn't load the images in the frontend, the votes didn't work for me even before. both are not a big deal for me anyway.

**Comment by mastervanleeuwen** [comment] 2023-09-15 19:55
Thanks for the reports. There was indeed a problem with the voting; I found the bug and it will be fixed in the next release candidate.

For the images, could you explain what you mean? I thought that you meant the photos, but looking at one of your pages: https://camminateinfriuli.it/index.php/component/jtg/track/vote?id=119&rate=2#jtg_param_header_rating
the photos seem to show up at the bottom of the page. Also on my test page:
https://jtrackgalleryj4.gta-trek.eu/index.php/en/track/31
the photos are visible. Please let me know if something is missing and I will have a deeper look.

**Comment by camminateinfriuli** [comment] 2023-09-16 07:55
I'm happy to help you, for me the voting mechanism is not essential, but it's a good idea if you fix this bug.

The other problem is that it doesn't upload the photos from the frontend, this isn't a huge problem for me either, even if it would be useful, for now I upload them from the backend.

**Closed** 2024-11-02 19:53 UTC
