### ISSUE TITLE
Error during the gpx import on Joomla 5

### ISSUE THREAD

**Issue by mambanero** [mastervanleeuwen/J-TrackGallery#91] opened 2024-10-02 13:23 UTC
Dear Marco,
see you again.
After installing the new version Joomla 5, I installed Jtrack in the latest update (9.35).
Trying to import some GPX track I find these message:
0 round(): Argument #1 ($num) must be of type int|float, string given
and I'm blocked...no possibility to continue...
Can you help me?

Regards

Mauro

**Comment by mastervanleeuwen** [comment] 2024-10-24 19:35
Hi Mauro,

This points to an error while parsing the GPX file. From this message alone, it is a bit difficult to pinpoint the cause of the issue. Would it be possible to send me one of the GPX files where this happens so that I can test and debug this a bit more? You can either post the file here or send it to me by e-mail.

Best regards, Marco.

**Comment by mambanero** [comment] 2024-10-25 07:03
Dear Marco,
thanks for your reply. I attach two differents GPX traces.
In this time I have found two differents problems that I tell you :
1) in the backend always the same error I wrote you sometime ago with both GPS files here attached
2) in the frontend, with admin access, I'm able to upload the GPX Strava file (Finalmente_ritorno_all_ebike_park_bissolo.zip) but never the trailfork GPX file (la-nera.zip)

I hope I have you given some trace on witch investigate...
Thanks a lot for your next reply.
Ciao
Mauro

[la-nera.zip](https://github.com/user-attachments/files/17517481/la-nera.zip)
[Finalmente_ritorno_all_ebike_park_bissolo.zip](https://github.com/user-attachments/files/17517491/Finalmente_ritorno_all_ebike_park_bissolo.zip)

**Comment by mastervanleeuwen** [comment] 2024-10-26 10:21
Hi Mauro,

Thanks for the report and the files, which helped me pinpoint the issue. This should be fixed in the latest pre-release: https://github.com/mastervanleeuwen/J-TrackGallery/releases/tag/0.9.36-rc3

There was a problem with reading time information in the GPX files; the reader only worked for cases when the time information is stored in UTC, and not for other time zones.

Best regards, Marco.

**Comment by mambanero** [comment] 2024-10-26 13:59
Dear Marco,

I can confirm you that the new release works fine and that JTrack works on Joomla 5!
Great job :)
Thanks a lot!
Ciao
Mauro

**Comment by mastervanleeuwen** [comment] 2024-11-02 19:43
Thanks for the test and the confirmation. This fix will also be included in the next full release of J!TrackGallery.

Best regards, Marco.

**Closed by mastervanleeuwen** 2024-11-02 19:43 UTC
