### ISSUE TITLE
Joomla 4 und php8

### ISSUE THREAD

**Issue by GStautner** [mastervanleeuwen/J-TrackGallery#11] opened 2021-12-07 14:21 UTC
Möchte gerne J!Track Gallery unter Joolma 4 weiterbenutzen und php 8 verwenden. Unter php 7.4 lief es sehr gut mit der Version 0.9.33

Jetzt unter php 8 gibt es Probleme
Non-static method JtgMapHelper::parseTracksInfoJS() cannot be called statically
/homepages/38/d820037332/htdocs/ZZZ_NeueSeiten/Joomla4/components/com_jtg/helpers/maphelper.php (135)

Habe die version: https://github.com/mastervanleeuwen/J-TrackGallery/archive/refs/tags/0.9.33a.zip getestet und sie läuft gut.

Habe doch noch ein Problem festgestellt - das Höhenprofil wird nicht angezeigt - nur graue Fläche

![grafik](https://user-images.githubusercontent.com/93383695/145045973-881ffd10-119c-4452-a4d1-5b8c2c402fd6.png)

Danke

**Comment by mastervanleeuwen** [comment] 2021-12-07 21:19
Thanks for your report.

This may be a Javascript error. Is your website accessible on the internet, so that I can have a look? If not, could you try the following:
1) Use the developer view of your web browser; this may show a Javascript error message.
2) Use the source view of you web browser to compare the page on you web site with a page on my Joomla 4 test site: https://jtrackgalleryj4.gta-trek.eu/index.php/component/jtg/track/16. In the source view, you should see something like this:
```
series: [
   {
      name: 'Elevation',
     unit: 'm',
     color: '#33FF66',
     yAxis: 0,
     data: [[0,1559],[0,1559],[0.01,1523],[0.01,1523], ....
```
and later on:
```
   <div id="profile" style="width:100%;" >
   <div class="profile-img" id="elevation" style="width:100%		; height: 180px;"></div>
   </div>
```
Best regards, Marco.

**Comment by GStautner** [comment] 2021-12-09 17:01
Hallo Marco,
Habe bei mir weder die Styles 'series' noch die Pfade nach id="elevation gefunden.

alle <g class=    gehen bei mir ab!

Falls du Zeit hast kannst du dir das Problem auf meiner Seite ansehen

https://j4.alpenverein-burgkirchen.de/index.php/component/jtg/track/71

Danke für deine Bemühungen

**Comment by mastervanleeuwen** [comment] 2021-12-12 22:58
Hello,
Thanks for the link. I investigated a little bit and made a change that may fix this issue. Could you try this one:

https://github.com/mastervanleeuwen/J-TrackGallery/archive/refs/tags/0.9.33b.zip

I don't have a server with PHP 8, so I could not fully test this myself. Please let me know if it works.

If it does not work, could you try to see whether you have a file 'error_log' in the main directory of your website and let me know whether it contains any error messages?

Best regards, Marco.

**Comment by GStautner** [comment] 2021-12-13 18:41
Hallo,

habe versucht die Stelle zu finden, wo das Chart ausgegeben werden sollte.
![grafik](https://user-images.githubusercontent.com/93383695/145867224-1d31ee74-0bb0-4a16-9111-b000612ba62c.png)

dann habe ich an der Stelle eine Ausgabe erzeugt
![grafik](https://user-images.githubusercontent.com/93383695/145867454-af645708-bb8b-4d3f-8887-fd42edb97cb9.png)

views/track/tmpl/default.php      ca. Zeile 540
	if ($havechart)
	{
	?>
    <div id="profile" style="width:<?php echo $this->cfg->charts_width; ?>;" >
	<div class="profile-img" id="elevation" style="width:<?php echo $this->cfg->charts_width; ?>
		; height: <?php echo $this->cfg->charts_height; ?>;"></div>
		<p> Hier fehlt die Ausgabe der Charts </p>
	</div>
	<?php
	}

Habe Error_reportimg auf Maximum gestellt - aber an der Stelle keinen Fehler gefunden. 
Nur vor der Ausgen der Seite -> folgende Fehlermeldung
![grafik](https://user-images.githubusercontent.com/93383695/145869572-7317ce57-b4b1-4614-a23b-cf4326b114a3.png)

**Comment by mastervanleeuwen** [comment] 2021-12-16 14:43
Hi,
Thanks for looking into this in more detail. The error messages that you see are related to special icons for way points that are missing (e.g a 'fast food' waypoint); I will try to implement a fix, but I think this is not the main problem. Could you send me the gpx file for this track for testing?

The part of the code that you indicate, which generates the graph, seems to work fine as far as I can see. However, there seems to be a problem with loading some javascript files; I would expect to see these lines:
```
<script src="/components/com_jtg/assets/js/ol.js"></script>
 <script src="/components/com_jtg/assets/js/jtg.js"></script>
 <script src="/components/com_jtg/assets/js/geolocation.js"></script>
 <script src="/components/com_jtg/assets/js/animatedCursor.js"></script>
```
when looking at the page with 'view source' in the browser. These lines are generated by the code in components/com_jtg/views/track/view.html.php, in lines 194 and further ( https://github.com/mastervanleeuwen/J-TrackGallery/blob/master/components/com_jtg/views/track/view.html.php#L194-L196 ).
I am not sure why these lines are not executed. 

If you are willing to try and investigate this in more detail, you could add commands in the source, like this 'error_log('I am here');' and the output will show up in the 'error_log' file on your web server. I will also try to do a few more tests myself, but have not yet been able to reproduce the error.

Best regards, Marco.

**Comment by GStautner** [comment] 2021-12-17 17:47
Hallo Marco,
habe die scripts in einen Beitrag eingefügt - laufen ohne Fehler

In der Datei view.html.php habe ich die Scripts überwacht
	// In the form view, $id would not be available for new files
          printf('vor ol.ls'."<br>");
			$document->addScript( JUri::root(true) . '/components/com_jtg/assets/js/ol.js');  // Load OpenLayers
          printf('vor its.js'."<br>");
			$document->addScript( JUri::root(true) . '/components/com_jtg/assets/js/jtg.js');
          printf('vor geolocation.js'."<br>");
			$document->addScript( JUri::root(true) . '/components/com_jtg/assets/js/geolocation.js');
			if ($this->params->get('jtg_param_disable_map_animated_cursor') == 0) {
				$document->addScript(JUri::root(true) . '/components/com_jtg/assets/js/animatedCursor.js');
			}
		
Ergebnis:
vor isset ($this->id)
vor ol.ls
vor its.js
vor geolocation.js
Übersicht Kategorien Tracks
alles ohne Fehler

In "/components/com_jtg/assets/js/jtg.js" habe ich überprüft ab Zeile 117
animatedCursorIcon = new ol.geom.Point( ol.proj.fromLonLat([3.79273,50.29782], jtgView.getProjection()));
	animatedCursorLayer.getSource().addFeature( new ol.Feature( { geometry: animatedCursorIcon } ) );
	addPopup(jtgMap);
    alert("am Ende von drawTrack");
![grafik](https://user-images.githubusercontent.com/93383695/146586139-d120577f-01c4-4b5e-890c-14cb422a0d5b.png)

Habe den Hintergrund auf transparent gestellt und z_Index geändert keine Veränderung
==================================================================

habe einen weiteren Fehler festgestellt , beim Download von tracks tritt der Fehler
 404
Seite nicht gefunden

/homepages/38/d820037332/htdocs/ZZZ_NeueSeiten/Joomla4/libraries/src/Router/Router.php (156)

ich habe eine Ausgabe erzeugt
	public function parse(&$uri, $setVars = false)
	{
      $datei = fopen("Fehler.txt","a");
		// Do the preprocess stage of the URL parse process
		$this->processParseRules($uri, self::PROCESS_BEFORE);
echo fwrite($datei, "\n nach PROCESS_BEFORE URI ist ".$uri,500);
		// Do the main stage of the URL parse process
		$this->processParseRules($uri);
echo fwrite($datei, "\n URI ist ".$uri,500);
		// Do the postprocess stage of the URL parse process
		$this->processParseRules($uri, self::PROCESS_AFTER);
echo fwrite($datei, "\n nach PROCESS_AFTER URI ist ".$uri,500);
		// Check if all parts of the URL have been parsed.
		// Otherwise we have an invalid URL   
fclose($datei);
    
		if (\strlen($uri->getPath()) > 0)
		{
			throw new RouteNotFoundException(Text::_('JERROR_PAGE_NOT_FOUND'));
		}
Fehler.txt:
nach PROCESS_BEFORE URI ist https://j4.alpenverein-burgkirchen.deindex.php?option=com_jtg&controller=download&task=download
 URI ist https://j4.alpenverein-burgkirchen.deindex.php?option=com_content&view=featured&controller=download&task=download&Itemid=210
 nach PROCESS_AFTER URI ist https://j4.alpenverein-burgkirchen.deindex.php?option=com_content&view=featured&controller=download&task=download&Itemid=210

Da geht ein "/" nach .de ab!!

Gruß Günther

**Comment by GStautner** [comment] 2021-12-19 08:13
<center><div id="jtg_map" class="olMap"></div><br /></center>
	<div id="popup" class="ol-popup">
   <a href="#" id="popup-closer" class="ol-popup-closer"></a>
   <div id="popup-content"></div>
</div>
    <div id="profile" style="width:100%;" >
	**_<div class="profile-img" id="elevation" style="width:100%		; height: 180px;"></div>_**
		<p> Hier fehlt die Ausgabe der Charts </p>
	</div>
		<div class="description"></div>
	<div class="gps-info-cont">

**Comment by mastervanleeuwen** [comment] 2021-12-27 22:11
Thanks for the report. The problem with the download button is fixed in this version:

https://github.com/mastervanleeuwen/J-TrackGallery/archive/refs/tags/0.9.33c.zip

It turns out that I had only tested this with Joomla 3.9.10 and it needed a few changes to make it work with Joomla 4. Could you try this version and let me know?

I also implemented a better handling of missing icons for waypoints, which may help with displaying the graphs as well. I am not sure whether this will fix it, so could you give this a try and let me know?

Best regards, Marco.

**Comment by GStautner** [comment] 2022-02-18 11:57
Habe immer noch Probleme mit Joomla 4.0 Php 8.0 oder 8.1 im Backend wenn ich eine neue Kategorie anlegen will

![grafik](https://user-images.githubusercontent.com/93383695/154678615-270a29fb-adad-426f-8ca9-c76c2f6bc7cf.png)
in der Datenbank ist es möglich

**Comment by marcovanleeuwen** [comment] 2022-02-18 17:01
Dear Gunther,

that is strange, I thought i had fixed this…

Could you check whether the file amdinistrator/components/com_jtg/views/cats/view.html.php has the following lines in it:
`      if (JVERSION >= 4.0) {
         $editor = JFactory::getApplication()->getConfig()->get('editor');
      }
      else 
      {
         $editor = JFactory::getConfig()->get('editor');
      }
      $editor = Editor::getInstance($editor);;
`

around line 190. Like the version here: https://github.com/mastervanleeuwen/J-TrackGallery/blob/master/administrator/components/com_jtg/views/cats/view.html.php ? Could it be that you are using an old version of this file?

Best regards, Marco.

**Comment by mastervanleeuwen** [comment] 2022-02-18 19:55
Dear Gunther,

Thanks for the report; that was a bug that affects Joomla 4. I have fixed it and released a new version:

**Comment by GStautner** [comment] 2022-02-18 20:07
Update war nicht gut
neue Iconen
![grafik](https://user-images.githubusercontent.com/93383695/154753710-401d98ad-2446-4125-ac5b-5663dd3497ec.png)

Tracks anzeigen leider jetzt ohne Karte

leider auch ohne meine Gehzeitberechnung - stelle alles wieder zurück
Gruß Günther

**Comment by GStautner** [comment] 2022-02-18 20:09
Sorry die Karte ist noch gekommen - hat nur lange gedauert

**Comment by mastervanleeuwen** [comment] 2022-02-18 22:34
I see, it worked on my test system, but the fix was not complete. I made another small fix in this version:
https://github.com/mastervanleeuwen/J-TrackGallery/releases/tag/0.9.34-rc3
(same version number, but it has an additional fix).
Could you try this one?

**Comment by mastervanleeuwen** [comment] 2022-06-19 20:19
This issue seems to be solved. I just released a new version with a number of other updates and fixes:
https://github.com/mastervanleeuwen/J-TrackGallery/releases/tag/0.9.34
Please open a new issue in case you encounter any problems.

**Closed by mastervanleeuwen** 2022-06-19 20:19 UTC
