### ISSUE TITLE
Problem create map

### ISSUE THREAD

**Issue by NicolasGavoille** [mastervanleeuwen/J-TrackGallery#45] opened 2023-01-23 17:48 UTC
Hi when i click on "new map" i have this message : Call to a member function getXml() on null 

Have you got a solution ?

**Comment by mastervanleeuwen** [comment] 2023-01-24 22:08
Hi Nicolas,

Thanks for your message; this was a bug in the current release. Could you try the latest development version from this page:
https://github.com/mastervanleeuwen/J-TrackGallery/releases/tag/0.9.34-rc25
The problem should be fixed there. Please let me know in case the problem is still there.

Best regards, Marco.

**Closed** 2023-09-03 10:48 UTC
