### ISSUE TITLE
allow download track for public user and other questions

### ISSUE THREAD

**Issue by mambanero** [mastervanleeuwen/J-TrackGallery#14] opened 2022-01-26 14:42 UTC
Dear Marco,
first of all thanks for developing this useful component(for me).
I found several things I don't understand.
1) How to allow everybody (also if not registered user) to dw the GPX track? Now it seems an action permitted only for registered users or whit another access level
2)The link in the overview map " GPS map" give an error page and I don't know how to change it
3)Some tracks have altitude and speed graph shown on the detail page of the track and others don't have this graph (it is shown a grey rectangle)
Here below the link where I've used your component
https://www.tidonvalley.com/index.php/trail1/jtg
I'm working to translate the component all into Italian if you want to add it to the next package.
Thanks in advance for your answer

Mauro

**Comment by mastervanleeuwen** [comment] 2022-01-26 19:58
Dear Mauro,

Thanks for your message. Great to hear that you are working on an Italian translation; I will be happy to include it in the language files. Do hesitate to ask if something is not clear to you; there may be some items in the language files that are not in use anymore.

To enable track downloads for anyone, you can allow 'Public' to download files, in the permissions tab of the J!Trackgallery settings (under 'Global Configuration'), like this:

![image](https://user-images.githubusercontent.com/23643853/151236879-369a2e28-f9b9-434f-8e12-774136975649.png)

For your second question: thanks for reporting this bug, I have a fix ready which I will upload to github in the next few days.

For the graphs, I think I understand the problem: some of you GPX files do not seem to have elevation data and this may be the reason; I will try to improve this in the coming days.

Best regards, Marco.

**Comment by mastervanleeuwen** [comment] 2022-01-27 16:11
Dear Mauro,

I prepared a new version with fixes for the problems that you report, which is available here: https://github.com/mastervanleeuwen/J-TrackGallery/releases/download/0.9.34-rc1/com_jtg.zip

I also noticed that there is a problem with rendering the gps tracks when showing individual tracks (it works well on the overview map), possibly because of some interference in the style sheets (css). I have updated the openlayers package to the latest version to see whether this fixes the issue.

Could you try this version and let me know whether it works?

Best regards, Marco.

**Comment by mambanero** [comment] 2022-01-28 07:25
Hi Marco,

thank you for your quick answer. I will try today the new version and I will give you my feedback as soon as possible.
I hop to finish the italian translation for the end of the week and I send you the zip file.
Keep in touch
Mauro

**Comment by mambanero** [comment] 2022-01-31 08:14
Dear Marco,
your last version works!
The only problem I found is that speed values in the speed chart for every trace are exagerates. About 80km/h. Yes I go fast but not so! ;) Can you verify, please?
Mauro

**Comment by mastervanleeuwen** [comment] 2022-02-01 15:52
Dear Mauro,

Thanks for pointing that out. This seems to be a feature of the gpx files. Looking at dh_blu.gpx:
`
<trkpt lat="44.90032" lon="9.29388">
<ele>539</ele>
<time>2020-11-19T00:27:00-08:00</time>
</trkpt>
<trkpt lat="44.90043" lon="9.29367">
<ele>544</ele>
<time>2020-11-19T00:27:01-08:00</time>
</trkpt>
<trkpt lat="44.90044" lon="9.29357">
<ele>544</ele>
<time>2020-11-19T00:27:02-08:00</time>
</trkpt>
` 
which shows that the times associated to the points are different by only 1 second each time.  The track is 1.2 km long, and there are about 84 points (the first point is at 00:27:00 and the last point is 00:28:23), so that would given about 60 km/h. Could it be that the time stamps are incorrect in the gpx file? Did you edit the file?

Best regards, Marco.

**Comment by mastervanleeuwen** [comment] 2022-02-13 15:48
Dear Mauro,

Thank you very much for the Italian translation. I have included the files in the latest version: https://github.com/mastervanleeuwen/J-TrackGallery/releases/tag/0.9.34-rc2

Best regards, Marco.

**Comment by LOM44** [comment] 2022-03-22 09:49
Hi,
how use only plugin because i use {JTRACKGALLERYMAP}5568737-track-grand-circuit.gpx{/JTRACKGALLERYMAP} but where i need to copy 5568737-track-grand-circuit.gpx file. i'm trying in images, in jtrackgellery/uploaded_tracks, but it doesn't works ...
Thanks

**Comment by cogulobi** [comment] 2022-06-19 15:08
> Dear Mauro,
> 
> Thanks for your message. Great to hear that you are working on an Italian translation; I will be happy to include it in the language files. Do hesitate to ask if something is not clear to you; there may be some items in the language files that are not in use anymore.
> 
> To enable track downloads for anyone, you can allow 'Public' to download files, in the permissions tab of the J!Trackgallery settings (under 'Global Configuration'), like this:
> 
> ![image](https://user-images.githubusercontent.com/23643853/151236879-369a2e28-f9b9-434f-8e12-774136975649.png)
> 
> For your second question: thanks for reporting this bug, I have a fix ready which I will upload to github in the next few days.
> 
> For the graphs, I think I understand the problem: some of you GPX files do not seem to have elevation data and this may be the reason; I will try to improve this in the coming days.
> 
> Best regards, Marco.

Hi Marco,
I followed your suggestion and it worked for a single access to the page. Now, if I retry to access the same page I get:

1064
You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ': htmlspecialchars() expects parameter 1 to be string, array given in /opt/l...' at line 3

Even if I newly switch to "not allowed" the problem persists and the only solution if to uninstall the package and reinstall it.

Best regards,
Corrado

**Comment by mastervanleeuwen** [comment] 2022-06-19 18:52
Hi Corrado,

Thanks for the report. I have tried to reproduce it, but did not manage so far. In the error message above, there is the following: 'array given in /opt/l...'. Is there a way to find out which file this happens in? Could you check the error_log file from your website?

Best regards, Marco.

**Comment by cogulobi** [comment] 2022-06-19 20:33
Hi Marco,
this is the content of the log file
==============================================================================================

2022-06-19T20:26:52+00:00	CRITICAL 127.0.0.1	error	Uncaught Throwable of type Joomla\Database\Exception\PrepareStatementFailureException thrown with message "You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ':  htmlspecialchars() expects parameter 1 to be string, array given in /opt/l...' at line 3". Stack trace: #0 [ROOT]/libraries/vendor/joomla/database/src/Mysqli/MysqliDriver.php(1048): Joomla\Database\Mysqli\MysqliStatement->__construct(Object(mysqli), 'SELECT a.*, b.t...')
#1 [ROOT]/libraries/vendor/joomla/database/src/DatabaseDriver.php(1900): Joomla\Database\Mysqli\MysqliDriver->prepareStatement('SELECT a.*, b.t...')
#2 [ROOT]/components/com_jtg/models/jtg.php(170): Joomla\Database\DatabaseDriver->setQuery(Object(Joomla\Database\Mysqli\MysqliQuery))
#3 [ROOT]/components/com_jtg/views/jtg/view.html.php(117): JtgModeljtg::getTracksData(NULL, NULL, ' AND ( ( a.acce...')
#4 [ROOT]/libraries/src/MVC/Controller/BaseController.php(697): JtgViewjtg->display()
#5 [ROOT]/components/com_jtg/controller.php(65): Joomla\CMS\MVC\Controller\BaseController->display()
#6 [ROOT]/libraries/src/MVC/Controller/BaseController.php(735): JtgController->display()
#7 [ROOT]/components/com_jtg/jtg.php(91): Joomla\CMS\MVC\Controller\BaseController->execute('')
#8 [ROOT]/libraries/src/Dispatcher/LegacyComponentDispatcher.php(69): require_once('/opt/lampp/htdo...')
#9 [ROOT]/libraries/src/Dispatcher/LegacyComponentDispatcher.php(71): Joomla\CMS\Dispatcher\LegacyComponentDispatcher::Joomla\CMS\Dispatcher\{closure}('/opt/lampp/htdo...')
#10 [ROOT]/libraries/src/Component/ComponentHelper.php(389): Joomla\CMS\Dispatcher\LegacyComponentDispatcher->dispatch()
#11 [ROOT]/libraries/src/Application/SiteApplication.php(204): Joomla\CMS\Component\ComponentHelper::renderComponent('com_jtg')
#12 [ROOT]/libraries/src/Application/SiteApplication.php(243): Joomla\CMS\Application\SiteApplication->dispatch()
#13 [ROOT]/libraries/src/Application/CMSApplication.php(278): Joomla\CMS\Application\SiteApplication->doExecute()
#14 [ROOT]/includes/app.php(63): Joomla\CMS\Application\CMSApplication->execute()
#15 [ROOT]/index.php(32): require_once('/opt/lampp/htdo...')
#16 {main}

============================================================================================

Best regards,
Corrado

**Comment by mastervanleeuwen** [comment] 2022-06-20 08:00
Hi Corrado,

Thanks for posting the log; it gives some more hints for the problem. I made a change to the code that might fix it. Could you try this version:
https://github.com/mastervanleeuwen/J-TrackGallery/releases/download/0.9.34-rc7/com_jtg.zip
and let me know whether it works?

Best regards, Marco.

**Comment by cogulobi** [comment] 2022-06-20 09:47
Hi Marco,
the problem seems to be solved, but, now, the two tables "latest tracks" and "most popular tracks" are empty (No data) and remain empty independently from what I do.
Another problem: if I select a category from the category page I get a 404 error.

Best regards,
Corrado

**Comment by cogulobi** [comment] 2022-06-21 18:54
P.S. - the problem appeared after the changes you introduced to allow the tracks download. Before that change the frames were correctly populated.

Corrado

**Comment by cogulobi** [comment] 2022-06-23 16:16
Hi Marco,
I think I found another small bug. In the GPS track page, if I have more than 20 tracks and I want to change the page I get a 404 error.
I've also found something in the administrative page. If I try to add a new category, I first get the following messages:

Notice: Undefined variable: default_overlays in /opt/lampp/htdocs/leviedellatransumanza4/administrator/components/com_jtg/views/cats/view.html.php on line 203

Notice: Undefined variable: size in /opt/lampp/htdocs/leviedellatransumanza4/administrator/components/com_jtg/views/cats/view.html.php on line 204

Warning: Invalid argument supplied for foreach() in /opt/lampp/htdocs/leviedellatransumanza4/libraries/src/HTML/Helpers/Select.php on line 523


Then, if I save the new category, I get the following error:

1364 Field 'ordering' doesn't have a default value 

and the category is not created. As I workaround, I'm currently renaming the existing categories, since I need less than 10 categories, but it would be better to have the possibility to freely add items.

Concerning the the missing list of "latest tracks" let me know if I can do some tests for you (I'm adding a figure with the problem).

Best regards,
Corrad
![Schermata del 2022-06-23 18-15-00](https://user-images.githubusercontent.com/29477197/175346397-9c131417-8283-48d8-b11b-d7519302bc68.png)
o

**Comment by mastervanleeuwen** [comment] 2022-06-23 20:01
Dear Corrado,

Thanks for the reports. I have fixed the problem with adding new categories in this version:
https://github.com/mastervanleeuwen/J-TrackGallery/releases/tag/0.9.24-rc10

That version also has some further tweaks in the SQL code and database handling for the lists with latest/most popular tracks. I am not sure whether this will fix it, but could you give it a try? If it does not work, I will add some more debug printout statements to try and understand the issue.

I could not reproduce the problem with showing the tracks after track 20 on my test system; I tried to reproduce it by adding more tracks here: 
https://jtrackgalleryj4.gta-trek.eu/index.php/component/jtg/files/list
but it works for me (note: you can also set the number of entries per page to 10 to test the behaviour with a smaller number of tracks). Could you try on that page and let me know whether it works for you?
Also this behaviour may point to some subtle difference between the database on your system and mine. Let me know what you find; if it does not work, we can also add debug statements there for a deeper look.

Best regards, Marco.

**Comment by cogulobi** [comment] 2022-06-24 07:10
Hi Marco,
I confirm the the categories is solved, thank you, Unfortunately, the others are still there.
I changed the number of tracks to be shown to 10 and to 30, but the problem persists.
I'm working in a xampp environment and with the following database:

10.4.24-MariaDB

Is it older than yours?

When I try to change page I get the following error:

#Fields: datetime	priority clientip	category	message
2022-06-24T06:55:42+00:00	CRITICAL 127.0.0.1	error	Uncaught Throwable of type Joomla\CMS\Router\Exception\RouteNotFoundException thrown with message "Pagina non trovata". Stack trace: #0 [ROOT]/libraries/src/Application/CMSApplication.php(1069): Joomla\CMS\Router\Router->parse(Object(Joomla\CMS\Uri\Uri), true)
#1 [ROOT]/libraries/src/Application/SiteApplication.php(820): Joomla\CMS\Application\CMSApplication->route()
#2 [ROOT]/libraries/src/Application/SiteApplication.php(228): Joomla\CMS\Application\SiteApplication->route()
#3 [ROOT]/libraries/src/Application/CMSApplication.php(278): Joomla\CMS\Application\SiteApplication->doExecute()
#4 [ROOT]/includes/app.php(63): Joomla\CMS\Application\CMSApplication->execute()
#5 [ROOT]/index.php(32): require_once('/opt/lampp/htdo...')
#6 {main}

and a very long list (thousands) of deprecated warnings similar to these ones:

2022-06-24T06:56:17+00:00	WARNING 127.0.0.1	deprecated	Joomla\CMS\Factory::getLanguage() is deprecated. Load the language from the dependency injection container or via Joomla\CMS\Factory::getApplication()->getLanguage().
2022-06-24T06:56:17+00:00	WARNING 127.0.0.1	deprecated	Joomla\CMS\Factory::getDbo() is deprecated. Load the database from the dependency injection container.
2022-06-24T06:56:17+00:00	WARNING 127.0.0.1	deprecated	Joomla\CMS\Factory::getDbo() is deprecated. Load the database from the dependency injection container.
2022-06-24T06:56:17+00:00	WARNING 127.0.0.1	deprecated	Support for registering functions is deprecated and will be removed in Joomla 5.0, use the service registry instead
2022-06-24T06:56:17+00:00	WARNING 127.0.0.1	deprecated	Support for a three segment service key is deprecated and will be removed in Joomla 5.0, use the service registry instead
2022-06-24T06:56:17+00:00	WARNING 127.0.0.1	deprecated	Joomla\CMS\Factory::getConfig() is deprecated. The configuration object should be read from the application.
2022-06-24T06:56:17+00:00	WARNING 127.0.0.1	deprecated	Joomla\CMS\Cache\Cache::getInstance() is deprecated. The cache controller should be fetched from the factory.
2022-06-24T06:56:17+00:00	WARNING 127.0.0.1	deprecated	Since joomla/application 2.0.0: Accessing the input property of Joomla\Application\AbstractWebApplication is deprecated, use the Joomla\Application\AbstractWebApplication::getInput() method instead.
2022-06-24T06:56:17+00:00	WARNING 127.0.0.1	deprecated	Joomla\CMS\Factory::getDbo() is deprecated. Load the database from the dependency injection container.
2022-06-24T06:56:17+00:00	WARNING 127.0.0.1	deprecated	Since joomla/event 2.0.0: Not passing an event object to Joomla\Event\Dispatcher::dispatch() is deprecated, as of 3.0 the $event argument will be required.
2022-06-24T06:56:17+00:00	WARNING 127.0.0.1	deprecated	Since joomla/event 2.0.0: Not passing an event object to Joomla\Event\Dispatcher::dispatch() is deprecated, as of 3.0 the $event argument will be required.
2022-06-24T06:56:17+00:00	WARNING 127.0.0.1	deprecated	Since joomla/application 2.0.0: Accessing the input property of Joomla\Application\AbstractWebApplication is deprecated, use the Joomla\Application\AbstractWebApplication::getInput() method instead.

Best regards,
Corrado

**Comment by cogulobi** [comment] 2022-06-24 07:12
P.S. - Your demo page works perfectly with my browser.

**Comment by mastervanleeuwen** [comment] 2022-06-24 22:17
Hi Corrado,

Thanks for testing again. I prepared a version here: 

https://github.com/mastervanleeuwen/J-TrackGallery/releases/tag/0.9.34-debug

which adds some debug printouts in the error_log that may help to track down what is going wrong. Could you install this version and navigate to the main page with the overview map and to the track list until it gives the error? Please send me the last few lines of error_log to inspect. On my system, I get the following:
```
[24-Jun-2022 12:48:35 UTC] 10 rows in result; without access selection; limit LIMIT 0,10
[24-Jun-2022 12:48:35 UTC] 10 rows in result; access selection: ( a.terrain LIKE '%%' AND 
a.level >= 1 ) AND 
( ( a.catid LIKE '%13%' OR a.catid LIKE '%10%' OR a.catid LIKE '%11%' OR a.catid LIKE '%16%' OR a.catid LIKE '%17%' OR a.catid LIKE '%14%' OR a.catid LIKE '%19%' OR a.catid LIKE '%15%' OR a.catid LIKE '%20%' OR a.catid LIKE '%21%' OR a.catid LIKE '%12%' ) ) AND a.access <= 0
```
and
```
[24-Jun-2022 22:05:41 UTC] jtgParseRoute 2 segments: files,list
[24-Jun-2022 22:05:41 UTC] jtgParseRouteCategory: routing files/list, 1 segments left
```
I had seen the deprecation messages as well, but they are warnings and should not affect the correct functioning of the code; I'll be working on fixing those as well, but there are quite a few of them and there is not always an immediate/simple fix.

Cheers, Marco.

**Comment by cogulobi** [comment] 2022-06-25 07:23
Hi Marco,
I do not see, in the log files, the lines you mentioned. Just to be sure: in the global configuration of the site I enabled the "log almost all" and "deprecated API" switches, is it sufficient? 
It is possible that the code never reaches the debug lines you introduced. My feeling is that the database has nothing to do with the problem but, conversely, we are facing a page link issue.
I also enabled the debug mode of the site and this is the result:

![Schermata del 2022-06-25 09-13-11](https://user-images.githubusercontent.com/29477197/175763149-b54fea1a-1d24-40c8-a0a5-e7784281455a.png)

**Comment by cogulobi** [comment] 2022-06-25 07:36
Sorry, I forgotten to mention that in my previous comment I was talking about the change of page problem (404 problem), but the log file does not show any output even when I navigate the overview page (No data problem).
Best regards,
Corrado

**Comment by mastervanleeuwen** [comment] 2022-06-25 08:42
Dear Corrado,

Thanks for checking. This should help further debugging, I will have a look. One more question for the 'page not found' issue. Could you go to the track list and check what the link at the bottom, for page 2, points to? On my test page it looks like this:
<img width="619" alt="image" src="https://user-images.githubusercontent.com/23643853/175765638-d14ad55c-b411-4dab-bc48-baa839582c0f.png">
(note that the mouse pointer is positioned on the '2' link and the link in the left bottom ends with 'start=20#', but the part before is probably what produces the error in your case; this is generated by some built-in joomla code, as far as I know...)

Best regards, Marco.

**Comment by cogulobi** [comment] 2022-06-25 08:58
Hi Marco,
here is the screenshot. The site I'm preparing is multi-language (by the way: it will be the Joomla4 version of this site www.leviedellatransumanza.org, in which I would like to add your extension), so the link is slightly different (can it be be reason of the problem?) 

![Schermata del 2022-06-25 10-50-53](https://user-images.githubusercontent.com/29477197/175766059-356b9ea7-206f-4dd1-854e-a492557f93ec.png)

Best regards,
Corrado

**Comment by mastervanleeuwen** [comment] 2022-06-25 09:43
Hi Corrado,

I see, I think the language part of the link '/en/' should work; it is dealt with by the Joomla framework. However, ther is an additional '3' after 'files/list' which may confuse the routing code. I have implemented a quick fix here:
https://github.com/mastervanleeuwen/J-TrackGallery/releases/tag/0.9.34-debug2
could you try that version?

I also added more debug printouts for the overview page with the track lists as well. Could you have another look at error_log to see whether anything line this shows up:
```
[25-Jun-2022 09:22:47 UTC] jtg view, got 15 tracks
[25-Jun-2022 09:22:47 UTC] jtg view, get latest track? jtg_param_newest: 10
[25-Jun-2022 09:22:47 UTC] jtg view, get latest track with parseTopNewest
```

I also noticed that the link has 'itemId=122' which is not generated by jTrackGallery, but probably by some other component. Do you happen to know where that might be coming from? I have encountered it before when helping someone else with their website, and may try to implement some protection against this.

Cheers, Marco.

**Comment by cogulobi** [comment] 2022-06-25 11:22
Hi Marco,
it seems that 3 is for English, while 1 is for Italian and 2 is for German. The problem is still there but the error message has changed

![Schermata del 2022-06-25 13-03-02](https://user-images.githubusercontent.com/29477197/175771067-1055553f-d2b7-46c3-aba3-1d276f21def2.png)

The lines you mentioned do not show up in the log file, which, however, changed

2022-06-25T11:04:23+00:00	CRITICAL 127.0.0.1	error	Uncaught Throwable of type Exception thrown with message "View not found [name, type, prefix]: list, html, jtgView". Stack trace: #0 [ROOT]/libraries/src/MVC/Controller/BaseController.php(646): Joomla\CMS\MVC\Controller\BaseController->getView('list', 'html', 'jtgView', Array)
#1 [ROOT]/components/com_jtg/controller.php(65): Joomla\CMS\MVC\Controller\BaseController->display()
#2 [ROOT]/libraries/src/MVC/Controller/BaseController.php(735): JtgController->display()
#3 [ROOT]/components/com_jtg/jtg.php(91): Joomla\CMS\MVC\Controller\BaseController->execute('')
#4 [ROOT]/libraries/src/Dispatcher/LegacyComponentDispatcher.php(69): require_once('/opt/lampp/htdo...')
#5 [ROOT]/libraries/src/Dispatcher/LegacyComponentDispatcher.php(71): Joomla\CMS\Dispatcher\LegacyComponentDispatcher::Joomla\CMS\Dispatcher\{closure}('/opt/lampp/htdo...')
#6 [ROOT]/libraries/src/Component/ComponentHelper.php(389): Joomla\CMS\Dispatcher\LegacyComponentDispatcher->dispatch()
#7 [ROOT]/libraries/src/Application/SiteApplication.php(204): Joomla\CMS\Component\ComponentHelper::renderComponent('com_jtg')
#8 [ROOT]/libraries/src/Application/SiteApplication.php(243): Joomla\CMS\Application\SiteApplication->dispatch()
#9 [ROOT]/libraries/src/Application/CMSApplication.php(278): Joomla\CMS\Application\SiteApplication->doExecute()
#10 [ROOT]/includes/app.php(63): Joomla\CMS\Application\CMSApplication->execute()
#11 [ROOT]/index.php(32): require_once('/opt/lampp/htdo...')
#12 {main}

I do not know which is the meaning of Itemid=122. In my installation the item no. 122 is the field editor (a plugin of Joomla). I have no idea of its purpose.

Best regards,
Corrado

**Comment by mastervanleeuwen** [comment] 2022-06-25 13:52
Hi Corrado,

OK, I think we are on the right track; I made a mistake in the previous version, which should be fixed in this one:
https://github.com/mastervanleeuwen/J-TrackGallery/releases/tag/0.9.34-debug3
Let me know whether this works. Could you also send me the log again, I would like to check whether there are any additional 'segments'  left in the routing code.

Best regards, Marco.

**Comment by cogulobi** [comment] 2022-06-25 14:27
Hi Marco,
now the track page switches correctly (in any language): good job!
The "No Data" problem is still there. The log file is empty...

Best regards,
Corrado

**Comment by mastervanleeuwen** [comment] 2022-06-25 17:35
Hi Corrado,
Glad it works; I will include the fix in the main version.

About the log file; it is strange that it is empty. Note that there are two log files, one 'error_log' in your main html/website directory and one in the admin subdirectory. The latter only logs errors from the admin section. Could it be that you were looking there instead of the one in your base directory?

Cheers, Marco.

**Comment by cogulobi** [comment] 2022-06-26 07:30
Hi Marco,
I did not find a second log file in the base directory. I made a search on the Internet, but such second file is not mentioned for Joomla 4

https://www.inmotionhosting.com/support/edu/joomla/joomla-4/log-settings/

My system is set as follows: the system debugging mode is enabled, error report maximum, and log almost all.

Let me know if there are other options I could activate.

Best regards,
Corrado

**Comment by mastervanleeuwen** [comment] 2022-06-26 08:09
Hi Corrado,

Ah, I see. The log file that I was referring to is the php log file, not the joomla log. You can turn on the logging of PHP errors in the php settings. I just realised that the location of the log file may vary from system to system; it can also be stored in `/var/log/httpd/error_log`, see for example the discussion here:
https://stackoverflow.com/questions/1678009/phps-configuration-setting-error-log-is-not-working

Let me know if you manage to find some of the messages in the log.

Best regards, Marco.

**Comment by cogulobi** [comment] 2022-06-26 08:32
Hi Marco,
found it! It was inside the system logs, named php_error log. Here is its content:

[26-Jun-2022 10:28:35 Europe/Berlin] jtgParseRoute 1 segments: jtg
[26-Jun-2022 10:28:35 Europe/Berlin] jtg view, got 0 tracks
[26-Jun-2022 10:28:35 Europe/Berlin] jtg view, get latest track? jtg_param_newest: 10
[26-Jun-2022 10:28:35 Europe/Berlin] jtg view, get latest track with parseTopNewest
[26-Jun-2022 10:28:35 Europe/Berlin] 10 rows in result; without access selection; limit LIMIT 0,10
[26-Jun-2022 10:28:35 Europe/Berlin] 0 rows in result; access selection: ( a.terrain LIKE '%Warning:  htmlspecialchars() expects parameter 1 to be string, array given in /opt/lampp/htdocs/leviedellatransumanza4/layouts/joomla/form/field/text.php on line 99%' AND 
a.level >= 1 ) AND 
( ( a.catid LIKE '%12%' ) ) AND a.access <= 0
[26-Jun-2022 10:29:29 Europe/Berlin] jtgParseRoute 2 segments: cats,default
[26-Jun-2022 10:29:32 Europe/Berlin] jtgParseRoute 1 segments: jtg
[26-Jun-2022 10:29:32 Europe/Berlin] jtg view, got 0 tracks
[26-Jun-2022 10:29:32 Europe/Berlin] jtg view, get latest track? jtg_param_newest: 10
[26-Jun-2022 10:29:32 Europe/Berlin] jtg view, get latest track with parseTopNewest
[26-Jun-2022 10:29:32 Europe/Berlin] 10 rows in result; without access selection; limit LIMIT 0,10
[26-Jun-2022 10:29:32 Europe/Berlin] 0 rows in result; access selection: ( a.terrain LIKE '%Warning:  htmlspecialchars() expects parameter 1 to be string, array given in /opt/lampp/htdocs/leviedellatransumanza4/layouts/joomla/form/field/text.php on line 99%' AND 
a.level >= 1 ) AND 
( ( a.catid LIKE '%10%' ) ) AND a.access <= 0

Best regards,
Corrado

**Comment by cogulobi** [comment] 2022-06-26 09:22
Hi Marco,
another little problem. The plugin field "show_link=false" in my installation is ignored: the link always shows.

Best regards,
Corrado

**Comment by mastervanleeuwen** [comment] 2022-06-26 10:22
Hi Corrado,

Thanks for sending the logs; I think I found the root cause and have implemented a fix in this version:
https://github.com/mastervanleeuwen/J-TrackGallery/releases/tag/0.9.34-rc11

For the plugin: there was an error in the documentation; please use 'show_link=0' or simply leave out the 'show_link' argument (the default is not to show it) to switch off the display of the link with the plugin.

Best regards, Marco.

**Comment by cogulobi** [comment] 2022-06-26 10:38
Hi Marco,
problem solved, compliment!
Concerning the plugin: 'show_link=0' or deleting the  shown_link argument do not solve the problem.

Best regards,
Corrado

**Comment by cogulobi** [comment] 2022-06-26 12:40
HI Marco,
forget what I said: the link has disappeared!

Corrado

**Comment by mastervanleeuwen** [comment] 2022-06-26 21:19
Thanks for the update and the good news! I'll prepare an official new release with all the fixes in the coming days.

Marco.

**Comment by cogulobi** [comment] 2022-06-27 07:33
Thank you to you for your valuable support!

Corrado

**Closed** 2023-08-27 17:06 UTC
