### ISSUE TITLE
error in JtrackGallery plugin

### ISSUE THREAD

**Issue by etabetamtb** [mastervanleeuwen/J-TrackGallery#73] opened 2023-10-09 07:48 UTC
Hallo,

I've just installed the complete package of JTG.
I've activated the plugin. I'm running it with Joomla 4.2.9.

I've tried to insert a GPX track inside one of my article using the syntax:

{JTRACKGALLERYMAP} id=19 {/JTRACKGALLERYMAP}

and I'm receiving the following error message:

in_array(): Argument #2 ($haystack) must be of type array, string given

the same happens if I use a syntax like:

{JTRACKGALLERYMAP} gpxfilename=XXXXXXX.gpx {/JTRACKGALLERYMAP}

Running the debug mode I get:

![image](https://github.com/mastervanleeuwen/J-TrackGallery/assets/147378099/62ad882b-3e9f-459d-9a94-f9b8e543b775)

I do not understand what it is wrong withg that

Thanks for any help

**Comment by mastervanleeuwen** [comment] 2023-10-11 11:24
Hi,

Thanks for the report. I checked the code, and found the place where the error is generated, but it is not clear to me why this happens. The plugin works well on my test website: https://jtrackgalleryj4.gta-trek.eu/index.php/en/plugin

Did you install the latest release candidate from here: https://github.com/mastervanleeuwen/J-TrackGallery/releases/tag/0.9.34-rc41 ? If the error persists with the latest version, could you try disabling the info section by switching off the 'show track details' in the plugin configuration:

<img width="907" alt="image" src="https://github.com/mastervanleeuwen/J-TrackGallery/assets/23643853/12cbc3e2-9e2a-4a74-a7ab-382cc939941b">

and let me know whether it works in that case?

Best regards, Marco.

**Comment by etabetamtb** [comment] 2023-10-11 12:47
Hi,

thanks for your feedback.
I confirm that I'm using the latest available version of the plugin.

I've implemented your suggestion and actually it worked. I've been able to see the map in my article.
And, moreover, I've enabled again the "show track detail" and it is still working well. No more error occurred.

Many thanks!

Simone

**Comment by mastervanleeuwen** [comment] 2023-11-23 11:33
Hi Simone,

Thanks for the feedback; there seems to be a problem in the way that the default settings are handled after installation. I have implemented a workaround that should fix the problem for future users in the latest pre-release:
https://github.com/mastervanleeuwen/J-TrackGallery/releases/tag/0.9.34-rc42

I will close this ticket; don't hesitate to report other problems or unexpected behaviour when you encounter them.

Best regards, Marco.

**Closed by mastervanleeuwen** 2023-11-23 11:33 UTC
